### ISSUE TITLE
Android: Upload blocks main thread (UI freezes)

### ISSUE THREAD

**Issue by beevelop** [frusdelion/tus-flutter-client#3]
**Describe the bug**
When triggering an upload, the UI freezes and the Flutter app becomes unresponsive for a few seconds.
Logging at the application logs reveals `skipped N frames`.

**To Reproduce**
Try uploading a semi-large file (50-100 MB) with Tus.

**Expected behavior**
The UI should stay responsive and keep responding to UI interactions.

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment: Android 10
- Used tus-android-client version: `0.1.9`
- Used tus-java-client version: `0.4.2`
- Used tus server software: `v1.3.0` | `52181920c22ef6391f69a8974dc1c495224d7209`

**Comment by onka13** [comment]
I've fixed this problem on my forked lib. Please check if it's working for you.

[https://github.com/onka13/tus-flutter-client/commit/da3bbec3c5b9d8cb8c09508c020bfd10cc6222ef](https://github.com/onka13/tus-flutter-client/commit/da3bbec3c5b9d8cb8c09508c020bfd10cc6222ef)

**Comment by Curvel** [comment]
Hey @onka13 I tested you fork now and that's the error I get from it:

Unsupported operationPlatformException(ErrorFromExecution, unexpected status code (405) while resuming upload, io.tus.java.client.ProtocolException: unexpected status code (405) while resuming upload
I/flutter (28788): 	at io.tus.java.client.TusClient.beginOrResumeUploadFromURL(TusClient.java:259)
I/flutter (28788): 	at io.tus.flutter.tus.HandleFileUpload$1.makeAttempt(TusPlugin.java:196)
I/flutter (28788): 	at io.tus.java.client.TusExecutor.makeAttempts(TusExecutor.java:85)
I/flutter (28788): 	at io.tus.flutter.tus.HandleFileUpload.doInBackground(TusPlugin.java:239)
I/flutter (28788): 	at io.tus.flutter.tus.HandleFileUpload.doInBackground(TusPlugin.java:150)
I/flutter (28788): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
I/flutter (28788): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
I/flutter (28788): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
I/flutter (28788): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
I/flutter (28788): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
I/flutter (28788): 	at java.lang.Thread.run(Thread.java:919)
I/flutter (28788): )

I changed the pubspec.yaml only.

**Comment by Extazx2** [comment]
Hello @onka13, I can't create issues in your fork, so I'm putting it here, since you reference your fork.

When using your fork, I get a 404, because it seems that your change from `resumeOrCreateUpload` to `beginOrResumeUploadFromURL` does not create the upload.

Do you know how I could change my app to try your fork ?

**Comment by onka13** [comment]
Hi @Curvel @Extazx2 , I've changed codes regarding to this comment [https://github.com/tus/tus-android-client/issues/19#issuecomment-390516753](https://github.com/tus/tus-android-client/issues/19#issuecomment-390516753). 
In my project I'm using this plugin for video upload to vimeo. 

Here is my pubspec.yaml

```
  tus:
    git:
      url: git://github.com/onka13/tus-flutter-client
```

Also you can test on your local after cloning the lib.

> git clone git://github.com/onka13/tus-flutter-client

```
  tus:
    path: ../tus-flutter-client
```

**Comment by Extazx2** [comment]
@onka13 Thanks for the reply however it did not answer my interrogations.

I've seen the comment and the changes, and that's why I'm asking how you use your own fork ?

`beginOrResumeUploadFromURL` doesn't create the upload, so my upload is failing because he can't begin something that hasn't been created

**Comment by onka13** [comment]
@Extazx2 I got it. For me I'm using vimeo and it's working without calling create firstly. 

1 - POST https://api.vimeo.com/me/videos
body: { "upload": {"approach": "tus", "size": "$size"}, }
response: { ... "upload": {  "upload_link": "URL" }}

2- Upload file to URL

```
Future<String> _uploadVideo(File file, String uploadLink,
      Function(double progress) onProgress) async {
    var completer = new Completer<String>();
    Tus tusD = Tus(uploadLink, allowCellularAccess: true);

    tusD.headers = <String, String>{
      "Tus-Resumable": "1.0.0",
      "Upload-Offset": "0",
      "Content-Type": "application/offset+octet-stream",
      "Accept": "application/vnd.vimeo.*+json;version=3.4"
    };

    tusD.onError = (String error, Tus tus) {
      print('tus onError');
      print(error);
      completer.completeError(error);
    };

    tusD.onProgress =
        (int bytesWritten, int bytesTotal, double progress, Tus tus) {
      onProgress(progress * 100);
    };

    tusD.onComplete = (String result, Tus tus) {
      print("tus onComplete $result");
      completer.complete(result);
    };

    var response = await tusD.initializeWithEndpoint();
    response.forEach((dynamic key, dynamic value) {
      print("tus init [$key] $value");
    });
    await tusD.createUploadFromFile(
      file.path,
      metadata: <String, String>{
        // additional metadata
        //"test": "message",
      },
    );
    return completer.future;
  }
```

I've checked the java code below and I think you are right. "beginOrResumeUploadFromURL" does not call createUpload.

[https://github.com/tus/tus-java-client/blob/master/src/main/java/io/tus/java/client/TusClient.java#L250](https://github.com/tus/tus-java-client/blob/master/src/main/java/io/tus/java/client/TusClient.java#L250)

**Comment by Extazx2** [comment]
Ok, thanks for the answer.

Also, what is the purpose of the edit on your "update tusplugin.m" commit ?

**Comment by onka13** [comment]
"resume" not working for vimeo uploads because of that vimeo has no create file method.

**Comment by Extazx2** [comment]
@onka13 Are you able to get upload progress with the package on iOS ?

I've created #9 to not polute this issue...

**Comment by onka13** [comment]
@Extazx2 Also It was not working for me then I've changed progressBlock part like this: 
[https://github.com/onka13/tus-flutter-client/blob/master/lib/tus.dart#L65](https://github.com/onka13/tus-flutter-client/blob/master/lib/tus.dart#L65)

**Comment by Extazx2** [comment]
> @Extazx2 Also It was not working for me then I've changed progressBlock part like this:
> https://github.com/onka13/tus-flutter-client/blob/master/lib/tus.dart#L65

I've also changed it as you did, but that did not change a thing...

**Comment by Extazx2** [comment]
@onka13 problem was not related, thanks anyway
